# Generated by Django 4.1.7 on 2023-05-01 09:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passenger',
            name='note',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='status',
        ),
        migrations.AddField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('En attente de passagers', 'En attente de passagers'), ('Validée', 'Validée'), ('Annulée', 'Annulée')], default='En attente de passagers', max_length=50),
        ),
        migrations.AlterField(
            model_name='course',
            name='creation_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
