# Generated by Django 4.1.7 on 2023-05-15 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_note_course_alter_course_creation_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='user',
        ),
        migrations.AddField(
            model_name='note',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='rated',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rated_evaluations', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='note',
            name='rater',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rater_evaluations', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='note',
            name='note',
            field=models.IntegerField(choices=[(1, '1 étoile'), (2, '2 étoiles'), (3, '3 étoiles'), (4, '4 étoiles'), (5, '5 étoiles')], default=5),
        ),
        migrations.DeleteModel(
            name='Evaluation',
        ),
    ]
