# Generated by Django 4.1.7 on 2023-05-20 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0004_remove_note_user_note_comment_note_rated_note_rater_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='vehicle_brand',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AddField(
            model_name='course',
            name='vehicle_model',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AddField(
            model_name='course',
            name='vehicle_seats',
            field=models.IntegerField(default=4),
        ),
    ]
